### ISSUE TITLE
requirements.txt not found

### ISSUE THREAD

**Issue by mruwnik** [rackerlabs/lambda-uploader#103]
When no requirements are provided, none are used. The problem is in Package.requirements() because when requires is None (as it is when nothing is provided), the default self._requirements_file is also set to None

**Comment by jarosser06** [comment]
This should be resolved on the master branch. I will try and get a new version out sometime today.

**Comment by jarosser06** [comment]
Version 1.0.1 is now in Pypi see if this resolves your problem.
