### ISSUE TITLE
Add --environment shell arg

### ISSUE THREAD

**Issue by bittlingmayer** [rackerlabs/lambda-uploader#125]
Thanks to https://github.com/rackerlabs/lambda-uploader/commit/4f8f3fcc5ca72c01fc4f435a59ea1f93e909988c the [environment](http://docs.aws.amazon.com/cli/latest/reference/lambda/create-function.html) variable is now supported.

It would be very useful to expose this as a shell arg, so developers could use it to pass keys that they do not wish to store in source code.  (In that case it could also good to support declaring them in the config, so that if they are not passed via the shell it fails fast.)

**Comment by jarosser06** [comment]
Looks like #124 should solve for this.

**Comment by jarosser06** [comment]
Closing since #124 was merged and adds the ability to pass environment variables via the CLI. Feel free to re-open if this does not address the issue.
