### ISSUE TITLE
Package Usage

### ISSUE THREAD

**Issue by ross-kruse** [rackerlabs/lambda-uploader#155]
This has been very helpful to upload files, but I have been unable to use any packages. 

All I am trying to do is run a package (I have tried both numpy and textblob) on my Python 3 lambda function and I cannot figure it out. I have a `lambda_handler` function inside my `lambda_function.py`and otherwise have no other file needs. 

I have tried installing the env in multiple different places but none of them seem to work. The error I keep getting is `Unable to import module 'lambda_function': No module named 'textblob'` 

The lambda function runs perfectly if I comment out the import line but as soon as as I add it back, I get the error message again. 

Any guidance would be greatly appreciated. I am working on a Mac. I know I am likely doing something wrong but I can't figure out what. I made sure the handler is `lambda_function.lambda_handler`

**Comment by jarosser06** [comment]
Are you importing the textblob python package? If you are but are not telling the lambda-uploader to install it in the lambda package then it would explain that error.
