### ISSUE TITLE
λ rather than Î» 

### ISSUE THREAD

**Issue by RyPoints** [rackerlabs/lambda-uploader#162]
lambda-uploader says:
```
Î» Building Package
Î» Uploading Package
Î» Fin
```

lambda-uploader used to say:
```
λ Building Package
λ Uploading Package
λ Fin
```

I'm using UTF8 in the terminal.  Is there a setting I need to change?

**Comment by jarosser06** [comment]
@RyPoints What version of lambda-uploader are you running and what version of Python?

**Comment by RyPoints** [comment]
@jarosser06 lambda-uploader 1.3.0 and Python 3.6.5.

**Comment by azatoth** [comment]
per https://xkcd.com/1172/ I'm actually using this behavior as a way to quickly see that I'm building the lambda under python 3.6 than under python 2.7
