### ISSUE TITLE
[HELP] Use existing virtual env instead of requirements.txt

### ISSUE THREAD

**Issue by BeyondEvil** [rackerlabs/lambda-uploader#166]
We use [pipenv](https://docs.pipenv.org/en/latest/) which has a `Pipfile` instead of a `requirements.txt`.

Is it possible to use the existing venv or have lamda-uploader use the Pipfile?

I'm happy to contribute a PR with some guidance.

**Comment by jarosser06** [comment]
Lambda Uploader doesn't support a Pipfile just a requirements file. You
should however be able to use an existing virtualenv though. Use
--virtualenv or -e to specify the existing virtualenv location.

If you want to create a PR for the Pipfile I would be happy to take a look.

**Comment by BeyondEvil** [comment]
Ok, sounds good!

I’ll check to see what level of work is required to make that happen. Without having looked at it at any depth, I’m afraid it would require lambda-uploader to have the entire pipenv lib as a dependency, which seems like overkill since there is a ”workaround” available.

**Comment by BeyondEvil** [comment]
As I was afraid, the parser is not a standalone module.
