### ISSUE TITLE
Extra copy of virtualenv is included in every zip file

### ISSUE THREAD

**Issue by martinb3** [rackerlabs/lambda-uploader#24]
It appears that we're storing an entire extra copy of the virtualenv in `.lambda_package/venv`, meaning that `.lambda_package/venv/lib/python2.7/site-packages/` is a duplicate of `.lambda_package/lambda_package`. I think we can skip the entire `venv` directory from being included in the .zip.

**Comment by martinb3** [comment]
I think I figured out what's going on here. Looking through the code, it refers to the `package` directory being zipped up, but there's actually two directories with that name -- `.lambda_package` and `lambda_package`. Since the file tree outside the zip had both, I had assumed the inside did too. Maybe we should name `.lambda_package` to something else to make it clear that it's a scratch space, _not_ the package to be zipped up?

**Comment by jarosser06** [comment]
PR #27 should help with this

**Comment by martinb3** [comment]
Fixed in #27.
