### ISSUE TITLE
Option zip and upload only the folder contents

### ISSUE THREAD

**Issue by dpurrington** [rackerlabs/lambda-uploader#31]
Right now, uploading grabs a bunch of stuff I don't need (git, PyGitHub, etc). This creates a fairly large zip file, hence, larger lambda storage.

Not being strong with Python, I'm guessing the extra stuff relates to using virtualenv. I don't need all those dependencies, and would prefer to pip install to the local directory. Could this be added as a new switch? Or is there something I'm missing and there's some other way for me to skip them?

**Comment by martinb3** [comment]
Hi @dpurrington -- I recently added the ability to [use an existing virtualenv](https://github.com/rackerlabs/lambda-uploader/pull/29) instead of building a new one on every upload using `-e` or `--virtualenv`. Does that satisfy your needs? You could build a local directory once, and just use `-e <local dir>` to have the uploader zip that up with the lambda function, instead of build a whole virtualenv.

**Comment by jarosser06** [comment]
@dpurrington lambda-uploader should only install and package whatever python dependencies you have specified in either a requirements.txt file or in your lambda.json file.

Could you paste your config so we can take a look?

**Comment by dpurrington** [comment]
I don't have a requirements file, and my requirements are empty.

**Comment by dpurrington** [comment]
lambda-uploader fails:  [Error 5] Access is denied: 'D:\\lambda\\python\\facility-service\\.lambda_package\\lambda_package\\.git\\objects\\76\\e8419181bf6c9ca0ce29476ebfd768b06ea48c'

**Comment by dpurrington** [comment]
Started with a fresh lambda to test this. I deleted the requirements object:
{
  "name": "uploader-test",
  "description": "testing lambda-uploader",
  "region": "us-east-1",
  "handler": "uploader-test.lambda_handler",
  "role": "xxxx",
  "timeout": 3,
  "memory": 128 
}

 The resulting zip file still has a lot of things in it:
![image](https://cloud.githubusercontent.com/assets/270433/11301665/e79a28fa-8f66-11e5-8187-b07720cc5f87.png)

**Comment by jarosser06** [comment]
@dpurrington Those are artifacts from the virtenv copy.  @martinb3 is currently working on a flag to omit the virtualenv altogether so that should ensure that you never have anything other than your files in the package.

**Comment by dpurrington** [comment]
Roger that. Just tried what he's working on and it is pretty close to what I was looking for. It does, however, include .lambda_uploader_temp in the zip file, which isn't needed.
