### ISSUE TITLE
Use the same names from boto functions for the lambda.json file

### ISSUE THREAD

**Issue by dpurrington** [rackerlabs/lambda-uploader#34]
Minor suggestion, but I think the lambda.json file should use the same names [that Boto is looking for](http://boto3.readthedocs.org/en/latest/reference/services/lambda.html#Lambda.Client.update_function_configuration). For example, instead of "name", use "FunctionName." Instead of "role" use "Role".

This will make it easy for people to add on scripts using the same json object (no translation layer required) and will make development of the module easier as well.

**Comment by jarosser06** [comment]
I think there is very minimal benefit here if any and this would just break all current deployments of the lambda-uploader.

**Comment by dpurrington** [comment]
You could do it in a way that was backwards compatible, and it would make adoption easier for your users (less documentation on your part, less for them to read and keep in their heads).
