### ISSUE TITLE
Cannot upload due to git pack file being locked

### ISSUE THREAD

**Issue by dpurrington** [rackerlabs/lambda-uploader#37]
I'm unable to build because a file in .lambda_uploader_temp cannot be deleted:
```
$ lambda-uploader.exe --config get.json
⁉️ Unexpected error. Please report this traceback.
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\lambda_uploader\shell.py", line 147, in main
    _execute(args)
  File "c:\python27\lib\site-packages\lambda_uploader\shell.py", line 64, in _execute
    venv, cfg.ignore)
  File "c:\python27\lib\site-packages\lambda_uploader\package.py", line 32, in build_package
    pkg.clean_workspace()
  File "c:\python27\lib\site-packages\lambda_uploader\package.py", line 51, in clean_workspace
    shutil.rmtree(self._temp_workspace)
  File "c:\python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "c:\python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "c:\python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "c:\python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "c:\python27\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "c:\python27\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 5] Access is denied: 'D:\\lambda\\python\\facility-service\\.lamba_uploader_temp\\lambda_package\\.git\\objects\\pack\\pack-22f84b49ef7d82978a5df62494ba39b3aa0147a4.idx'
```

Any idea what's going on? I tried blasting the folder and recloning my repo, but got the same result. Interestingly, it does not happen on my Mac, only on Windows. I also ran handle.exe looking for handles on this path, but there were none, which suggests the lock is in the Python process.

Also, using the switch to skip cleanup doesn't skip cleanup (see the Package class, build fcn).

**Comment by jarosser06** [comment]
It looks like its a file permissions error on that specific file.  Have you checked the permissions to make sure the user your running as has permission to remove that file?

https://github.com/rackerlabs/lambda-uploader/blob/master/lambda_uploader/package.py#L38-L42
--no-clean is working, if you notice the code is calling the cleanup methods before it attempts to create a new package.  --no-clean just means that the lambda-uploader won't clean up after its done, it still has to clean up before it attempts to create a new package.

**Comment by dpurrington** [comment]
I see. I'm running as admin (Windows, natch), and it's the same process creating the file and then trying to delete it (I watched it using procmon).

**Comment by jarosser06** [comment]
Have you tried removing the file manually?

You can try adding ".git/*" to the ignore section of the configuration file unless you purposely want it to package the entire .git directory as well.  I'm afraid I'm out of my depth when it comes to Windows.

**Comment by dpurrington** [comment]
I can rm -rf ./.lambda_uploader_temp no problem. I haven't added this repo (or the parent folder); it was added by lambda-uploader when I ran it. It's not in my repo.

**Comment by jarosser06** [comment]
Anything in that lambda_package directory that isn't from virtualenv would have come from the directory your lambda function is in.  

Are you sure that the directory your passing the lambda-uploader does not have a .git subdirectory?

**Comment by dpurrington** [comment]
o_O wait what? Yes, it does, so I guess that's the issue. It would be nice to support that as I'd like to be able to have this simple lambda described at the root level of a repo. For now, I'll make a src dir.

**Comment by jarosser06** [comment]
You can still keep it in the repo you just need to tell the lambda-uploader to ignore the .git directory when it copies everything to build the package.

https://github.com/rackerlabs/lambda-uploader#configuration-file

Adding that .git directory to ignore should prevent this issue.

**Comment by dpurrington** [comment]
Sweet! Thanks, Jim!

**Comment by jarosser06** [comment]
Glad to help!
