### ISSUE TITLE
Python 2.6 incompatible - I think that lambda-uploader complain

### ISSUE THREAD

**Issue by ps-jay** [rackerlabs/lambda-uploader#41]
Hi there,

I've just tried lambda-uploader on CentOS 6...  with Python 2.6..  ooops!
It of course doesn't work very well - but understandably - Python 2.6 is very out-of-date and Lambda itself uses 2.7.

I think that lambda-uploader should detect a non-Python 2.7 environment and refuse to work.
Else, it _seems_ to work, but ends up producing a zero-byte ```lambda_function.zip``` - which is just confusing.

If you think this is a good idea, I'm happy to work on a PR to implement.

Thoughts?

**Comment by jarosser06** [comment]
I don't think anyone up til now anyone has tested with Python 2.6 and I'm not sure that is a version of Python that should be supported with this project.  I like your idea, if you have time to work on a PR that would be great. :smile:

**Comment by ps-jay** [comment]
Cool, PR #42 opened.
Closing this.
