### ISSUE TITLE
UTF-8 Error

### ISSUE THREAD

**Issue by RyPoints** [rackerlabs/lambda-uploader#47]
Once I had lambda-uploader working I wrote a little utility script to copy my function.py to a '.λ' directory with its lambda.json.  Basically, I wanted to be able to have the same code and do:

λscript --production
Are you sure?! (yes/no)

λscript
(that would just upload integration by default)

Everything worked fine when I named the directory '.1.'  If I named it '.λ' I get:

λ Building Package
⁉️ Unexpected error. Please report this traceback.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/lambda_uploader/shell.py", line 151, in main
    _execute(args)
  File "/usr/local/lib/python2.7/site-packages/lambda_uploader/shell.py", line 64, in _execute
    venv, cfg.ignore)
  File "/usr/local/lib/python2.7/site-packages/lambda_uploader/package.py", line 41, in build_package
    pkg.prepare_virtualenv()
  File "/usr/local/lib/python2.7/site-packages/lambda_uploader/package.py", line 86, in prepare_virtualenv
    self.build_new_virtualenv()
  File "/usr/local/lib/python2.7/site-packages/lambda_uploader/package.py", line 112, in build_new_virtualenv
    raise Exception('virtualenv returned unsuccessfully')
Exception: virtualenv returned unsuccessfully

**Comment by jarosser06** [comment]
Try turning up the verbosity when running the command. It looks like virtualenv is failing to create have you tried runing virtualenv manually and creating a virtualenv inside that directory?

**Comment by RyPoints** [comment]
The cause of this error was definitely the λ character being included in the path name, the λ being part of UTF-8 but not ASCII.  You should be able to reproduce it this way.

**Comment by jarosser06** [comment]
When you ran virtualenv manually what was the output?

**Comment by RyPoints** [comment]
I didn't for this crash.  What I did was rename .λ to .functionName-uploader and it worked.

**Comment by jarosser06** [comment]
There is nothing specific from that output.  I either need output from running virtualenv inside that Unicode directory manually or I will need the output from -VV.

**Comment by RyPoints** [comment]
Did you try creating a directory named '.λ', putting any function.py and lambda.json in there and running lambda-upload?  I think that would allow you to recreate this error.

**Comment by jarosser06** [comment]
I am unable to reproduce your issue. Perhaps your system Python is not working with Unicode characters correctly.

`lambda-uploader --no-upload -VV
λ Building Package
INFO:lambda_uploader.package:Building new virtualenv and installing requirements
DEBUG:lambda_uploader.package:Virtualenv stdout: Using base prefix '/usr'
New python executable in /home/jim/Projects/.λ/.lamba_uploader_temp/venv/bin/python3
Also creating executable in /home/jim/Projects/.λ/.lamba_uploader_temp/venv/bin/python
Installing setuptools, pip, wheel...done.

DEBUG:lambda_uploader.package:Virtualenv stderr: 
DEBUG:lambda_uploader.package:Installing requirements found [u'Jinja2==2.8'] in config
DEBUG:lambda_uploader.package:Pip stdout: Collecting Jinja2==2.8
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting MarkupSafe (from Jinja2==2.8)
Installing collected packages: MarkupSafe, Jinja2
Successfully installed Jinja2-2.8 MarkupSafe-0.23

DEBUG:lambda_uploader.package:Pip stderr: You are using pip version 7.1.2, however version 8.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

INFO:lambda_uploader.package:Copying site packages
INFO:lambda_uploader.utils:Copying source files
INFO:lambda_uploader.package:Copying lib64 site packages
INFO:lambda_uploader.utils:Copying source files
INFO:lambda_uploader.utils:Copying source files
DEBUG:lambda_uploader.utils:Copying /home/jim/Projects/.λ/function.py to /home/jim/Projects/.λ/.lamba_uploader_temp/lambda_package/
DEBUG:lambda_uploader.utils:Copying /home/jim/Projects/.λ/lambda.json to /home/jim/Projects/.λ/.lamba_uploader_temp/lambda_package/
INFO:lambda_uploader.package:Creating zipfile
DEBUG:lambda_uploader.package:Zipping /home/jim/Projects/.λ/.lamba_uploader_temp/lambda_package/function.py as function.py
DEBUG:lambda_uploader.package:Zipping /home/jim/Projects/.λ/.lamba_uploader_temp/lambda_package/lambda.json as lambda.json
λ Fin`
