### ISSUE TITLE
JSON Serialization or MemoryError

### ISSUE THREAD

**Issue by RyPoints** [rackerlabs/lambda-uploader#48]
So, I got another error.  I have two near-identical functions with different lambda.json's.  One works, one does not.

### Working:
{
  "name": "integrationFunctionName",
  "description": "Description. Documentation: https://web.site",
  "region": "us-west-2",
  "handler": "integration.lambda_handler",
  "role": "arn:aws:iam::1234:role/app-int-lambda",
  "requirements": ["selenium", "pillow", "pynamodb"],
  "ignore": [
    ".git",
    "/*.pyc"
  ],
  "timeout": 30,
  "memory": 512
}

This one uploads and functions as expected.

### Non-working:

{
  "name": "functionName",
  "description": "Description. Documentation: https://web.site",
  "region": "us-west-2",
  "handler": "production.lambda_handler",
  "role": "arn:aws:iam::1234:role/app-prod-lambda",
  "requirements": ["selenium", "pillow", "pynamodb"],
  "ignore": [
    ".git",
    "/*.pyc"
  ],
  "timeout": 30,
  "memory": 512
}

This one errors out right after the upload starts.

### From lambda-uploader -VV
DEBUG:botocore.auth:Signature:
91f37147018cbb1bc394be46317c60593960212b809510e4f800fee436a70538
DEBUG:botocore.endpoint:Sending http request: <PreparedRequest [GET]>
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): lambda.us-west-2.amazonaws.com
DEBUG:botocore.vendored.requests.packages.urllib3.connectionpool:"GET /2015-03-31/functions/functionName/configuration HTTP/1.1" 404 106
DEBUG:botocore.parsers:Response headers: {'x-amzn-requestid': '8e7d7e55-c6d9-11e5-9312-bfc6b2d91d64', 'content-length': '106', 'connection': 'keep-alive', 'date': 'Fri, 29 Jan 2016 22:42:20 GMT', 'content-type': 'application/json', 'x-amzn-errortype': 'ResourceNotFoundException:http://internal.amazon.com/coral/com.amazonaws.awsgirapi/'}
DEBUG:botocore.parsers:Response body:
{"Message":"Function not found: arn:aws:lambda:us-west-2:1234:function:functionName","Type":"User"}
DEBUG:botocore.hooks:Event needs-retry.lambda.GetFunctionConfiguration: calling handler <botocore.retryhandler.RetryHandler object at 0x7efe3cc94910>
DEBUG:botocore.retryhandler:No retry needed.
DEBUG:lambda_uploader.uploader:function not found creating new function
DEBUG:lambda_uploader.uploader:running create_function_code
⁉️ Unexpected error. Please report this traceback.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/lambda_uploader/shell.py", line 151, in main
    _execute(args)
  File "/usr/local/lib/python2.7/site-packages/lambda_uploader/shell.py", line 82, in _execute
    upldr.upload(pkg)
  File "/usr/local/lib/python2.7/site-packages/lambda_uploader/uploader.py", line 112, in upload
    self.version = self.upload_new(pkg)
  File "/usr/local/lib/python2.7/site-packages/lambda_uploader/uploader.py", line 89, in upload_new
    Publish=self._config.publish,
  File "/usr/lib/python2.7/dist-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/dist-packages/botocore/client.py", line 382, in _make_api_call
    api_params, operation_model)
  File "/usr/lib/python2.7/dist-packages/botocore/client.py", line 423, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/lib/python2.7/dist-packages/botocore/validate.py", line 275, in serialize_to_request
    operation_model)
  File "/usr/lib/python2.7/dist-packages/botocore/serialize.py", line 412, in serialize_to_request
    serialized, shape, shape_members)
  File "/usr/lib/python2.7/dist-packages/botocore/serialize.py", line 457, in _serialize_payload
    partitioned['body_kwargs'], shape)
  File "/usr/lib/python2.7/dist-packages/botocore/serialize.py", line 520, in _serialize_body_params
    return json.dumps(serialized_body).encode(self.DEFAULT_ENCODING)
MemoryError

**Comment by RyPoints** [comment]
Also got a:

 File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)

At the end of that sometimes.  I tried re-saving the lambda.json in both ASCII and UTF-8 without it changing anything.

**Comment by jarosser06** [comment]
MemoryError seems to suggest that you ran out of memory during execution and I am unable to reproduce this error. Also its not your JSON configuration file its the results of a boto3 operation that is throwing the error.

**Comment by RyPoints** [comment]
This looks like it might relate to this:
https://github.com/aws/aws-cli/issues/1605

**Comment by RyPoints** [comment]
It appears this error may relate to the size of the .zip generated.  Strangely, if I run lambda-uploader --no-upload on my personal machine I get a 33.2MB zip.  When I run lambda-uploader --no-upload on the machine where I am getting the error I get a 76.5MB zip.

**Comment by martinb3** [comment]
> When I run lambda-uploader --no-upload on the machine where I am getting the error I get a 76.5MB zip.

The current package maximum size is 50mb for Lambda.

**Comment by RyPoints** [comment]
I figured out what was causing this, but it wasn't the ultimate cause of the problem.  I wrote a quick wrapper script around lambda-uploader and the wrapper script has many extra libraries for interacting with the linux filesystem.  I had that file in the same directory as the function.py and so it looks like it's dependencies got included in the virtual environment.

Without that I'm back to my original 31 meg zip file, but I get the exact same error.  It's puzzling because it works with nearly identical lambda.json files.

**Comment by martinb3** [comment]
@RyPoints If you could test without your wrapper, we might be able to eliminate that code from being the problem?

**Comment by RyPoints** [comment]
I already tried it both with and without the wrapper before posting.  I got the same error both ways.

**Comment by RyPoints** [comment]
If there's anything else you'd like me to try though let me know and I'll do so today.

**Comment by RyPoints** [comment]
The one that was working also no longer works.  You get the same message with both.

**Comment by RyPoints** [comment]
If I delete the function and try lambda-uploader I get this error at the end instead:

```
  File "/usr/local/lib/python2.7/site-packages/botocore/validate.py", line 273, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Unknown parameter in input: "Publish", must be one of: FunctionName, Runtime, Role, Handler, Description, Timeout, MemorySize, Code
```

**Comment by jarosser06** [comment]
What does your lambda.json file look like? If it has "Publish" and it is capitalized then you need to drop the P to p.

**Comment by RyPoints** [comment]
The lambda.json is already at the top of this issue report.  It does not have "Publish" in it currently in either case.

However, I went into the lambda-uploader in uploader.py code and did this:

```
def upload_new(self, pkg):
        with open(pkg.zip_file, "rb") as dil:
            zip_file = fil.read()

        LOG.debug('running create_function_code')
        response = self._client.create_function(
            FunctionName=self._config.name,
            Runtime='python2.7',
            Handler=self._config.handler,
            Role=self._config.role,
            Code={'ZipFile': zip_file},
            Description=self._config.description,
            Timeout=self._config.timeout,
            MemorySize=self._config.memory,
            **# Publish=self._config.publish,**
        )
        LOG.debug("AWS create_function response: %s" % response)

        return response.get('Version')
```

After doing that, the function uploaded without issue.

**Comment by martinb3** [comment]
Could you confirm which version of boto3 you're using?

**Comment by RyPoints** [comment]
### pip show boto3
---
Metadata-Version: 2.0
Name: boto3
Version: 0.0.22
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /usr/local/lib/python2.7/site-packages
Requires: botocore, jmespath, futures

### pip show botocore
---
Metadata-Version: 2.0
Name: botocore
Version: 1.0.0rc1
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /usr/local/lib/python2.7/site-packages
Requires: jmespath, python-dateutil, docutils
[rdavis@ip-10-31-36-159 balanceBeam]$

**Comment by jarosser06** [comment]
We need to set a boto3 version in the setup.py.  Try upgrading boto3 to > 1.0.0 and see if you still see that issue.

**Comment by RyPoints** [comment]
That's what pip said.  My pip is from my Python 2.7 installation and that's the version I use with lambda-uploader.

I commented out Publish=self._config.publish and the Publish=False reference in the other def above it and everything works great again, even my wrapping of the lambda-uploader, so I'm ecstatically content. :)

**Comment by martinb3** [comment]
It sounds like this ended up being a case where the PyPi dependencies were broken on a particular system. I'm guessing you're using an older AMI, @RyPoints, as even the version of Boto3 you're using dates back to Jun 18, 2015 (0.0.22, vs 1.2.3 from December 2015).

**Comment by RyPoints** [comment]
Since this was created I've fully diagnosed this error.  The problem was not the boto version.  I later set boto to 1.2.2 and got the same error.  The problem is with running boto on a low memory machine.  The line json.dumps(serialized_body).encode(self.DEFAULT_ENCODING) will crash on a large JSON encoding with a memory error.  It's a known issue with doing json.dumps on low-end machines:

http://stackoverflow.com/questions/24239613/memoryerror-using-json-dumps

I was using a t2.nano.  I upgraded to a t2.micro and no more memory error.

**Comment by sibblegp** [comment]
I had this same problem.  Upgrading my instance size fixed it.

**Comment by paulca99** [comment]
I'm having a similar issue now, and really don't want to increase my instance size. I'm uploading a 30M jar file using upload-function-code .... the t3.micro has 600M free memory ..... why does it run out of Memory ?
