### ISSUE TITLE
Warn if lambda-package is over current maximum package size

### ISSUE THREAD

**Issue by martinb3** [rackerlabs/lambda-uploader#49]
We should issue a warning if the zip file ends up larger than [the maximum](http://docs.aws.amazon.com/lambda/latest/dg/limits.html) for Lambda. It's currently 50mb.

**Comment by RyPoints** [comment]
:+1:

**Comment by tomislater** [comment]
:+1:

**Comment by tomislater** [comment]
I am going to do this.

**Comment by jarosser06** [comment]
I merged in the change however I wonder whether this should be a failure condition.  @martinb3 Thoughts?

**Comment by martinb3** [comment]
I figured a warning seemed better since if it ever gets raised, lambda-uploader will still work until we can get to removing the warning.

**Comment by jarosser06** [comment]
I've never attempted to upload something > or 50MB so do we know whether it will fail in boto3? I'm just thinking I would rather fail before the upload even starts than wait for the upload to fail while in progress.

**Comment by martinb3** [comment]
I am thinking about making it as future proof as possible -- I'd rather just warn the user and the user can decide to interrupt or not.

**Comment by jarosser06** [comment]
What about an optional failure flag if the size is greater than 50MB. I think If this issue popped up during a CD job I would want it to fail early and notify rather than waste resources.

**Comment by martinb3** [comment]
I think the resources wasted (in terms of AWS costs) are on the order of hundreths or thousandths of a cent, but I think a way to fail faster is a reasonable feature.

**Comment by jarosser06** [comment]
I'll have to think about what that might look like. This issue can be closed though. Thanks for the PR @tomislater

**Comment by tomislater** [comment]
No problem!
