### ISSUE TITLE
Easy sharing of code between lambda functions

### ISSUE THREAD

**Issue by timpitman** [rackerlabs/lambda-uploader#63]
Is there a way to share python code between lambdas, without having to create an additional package to install via requirements?

e.g., in the Serverless framework, there's the concept of a "lib" folder which can contain modules shared between multiple lambdas.

**Comment by jarosser06** [comment]
So one way to do it is to keep all of your code for your lambda modules in a single package and specify that package. Currently only master gives you the power to do something like this since it allows you to specify your requirements file, extra files, etc.

So one option for you is to try master and use the extra-file flag to specify that extra package to be packaged with your lambda-function. We have a few more features we want to get added to work with a multi-lambda function single Python package workflow in order to make it more efficient as well.

**Comment by timpitman** [comment]
Thanks, I had a go with source from master.  I think a tweak to the extra-files flag should work in my case where the specific lambda and common code are both sub-modules at the same level.  The current functionality puts the contents of the extra-files folder in the base level of the zip, the tweak would be to put the contents in a folder within the zip which has that original name.

**Comment by martinb3** [comment]
> the tweak would be to put the contents in a folder within the zip which has that original name

I see what you're getting at here, however I added the 'extra files' functionality with a few use cases in mind, and forcing extra files into a specific folder inside the zip will break some of those other use cases. 

I'd recommend making that extra folder on the source side, and then it will be copied recursively to the destination in that same structure. Then you'll be able to use this project as-is without maintaining any workaround. :)

**Comment by timpitman** [comment]
Making the folder on the source side does work and solves the problem for now, the limitation is that a different import statement is required to run the lambda locally compared to running on AWS.  The local case could be fixed with path manipulation (either at the shell or in python).

Thanks for the tips!

**Comment by thesmallestduck** [comment]
just noting an additional difficulty to having a different directory structure locally than in a real lambda environment is that it makes writing unit tests in a simple manner more challenging. Anything importing code from the 'shared source directory' will need do some contortions to make local unit testing possible.

**Comment by timpitman** [comment]
Yes - eg. my current contortions in the lambda function:

try:
    from lambda_operator.operator import OperatorSettings
except ImportError:
    from lambda_common.lambda_operator.operator import OperatorSettings

By creating the folder (in this case "lambda_common") in the lambda zip (rather than copying those files to the base of the zip), it would avoid the contortion.

**Comment by jarosser06** [comment]
That seems like a fair concern. I'll take a look at updating the extra files functionality to support this condition.

**Comment by martinb3** [comment]
I feel like sharing Python code is a solved problem -- and we're building something to make it possible in a different way than the standard Python ways of sharing code. Feels like we're reinventing the wheel here.

**Comment by thesmallestduck** [comment]
@martinb3 I don't think we (at least 'I') _want_ to support modifying import paths, it's just that given the current pattern of not preserving the directory structure when passed extra files for packaging, such modification becomes necessary. Apologies if I misunderstood what you were suggesting.

**Comment by martinb3** [comment]
> given the current pattern of not preserving the directory structure when passed extra files for packaging

If you pass a directory, it will preserve the structure, just FYI.

**Comment by thesmallestduck** [comment]
sorry for being unclear, I meant the root directory. when I do something like this:

```ambda-uploader --extra-files shared_source ./my_lambda```

and shared_source is a directory, the files inside shared_source are placed at the root level in the package, rather than inside a directory called shared_source.

**Comment by martinb3** [comment]
@thesmallestduck indeed, if we included `shared_source` in your example, I imagined someone would do:

```
mkdir extra_files
mv shared_source extra_files/
lambda-uploader --extra-files extra_files ./my_lambda
```
Alternately, do you need `--extra-files` for this use case at all? lambda-uploader already copies everything in the package directory into the package zip, recursively, no?

See https://github.com/rackerlabs/lambda-uploader/blob/master/lambda_uploader/package.py#L240.

**Comment by thesmallestduck** [comment]
perhaps ```extra-files``` will not be suitable for the code sharing I'm imagining. I must admit organizing my code base in such a way that multiple lambdas with shared code can be deployed from a project without rolling them all into the same package has been troublesome. Regardless, I have found this project very useful.

**Comment by martinb3** [comment]
I deliberately intended `--extra-files` to cover sharing code that wasn't in the same directory or a subdirectory of the lambda function's source, since anything in the same directory or nested deeper would be recursively copied in anyway.

**Comment by martinb3** [comment]
Perhaps a unit test with the structure you're imagining would help us understand the use case better, and make some changes to make it pass? :)

**Comment by jarosser06** [comment]
So I just want to make sure I understand this request.

Currently --extra-files will only pull files inside whatever directory you give it and move them to the top level of the lambda package.

This request is that --extra-files ./foo would create /foo in the lambda package is this correct?

**Comment by thesmallestduck** [comment]
imagine a project directory structure like so:

```
root_project_dir/
    shared_source/
        shared_package.py
    lambda_a/
        lambda_command.py
        tests/
            test_shared_package.py
```

imports of code from the shared_source directory inside lambda_a look like so:

```from shared_source.shared_package import foo```

and one can execute

```python -m unittest discover lambda_a```

from the root directory. The issue is that the previous import will work locally in this way, but will not work in the lambda given that the ```shared_source``` directory is not included when it is listed in the ```--extra-files``` flag

**Comment by jarosser06** [comment]
Thanks that confirms my understanding. After discussing offline I believe @martinb3 is going to work on this functionality.

**Comment by thesmallestduck** [comment]
that's great! apologies if my previous explanations were unclear.

**Comment by jarosser06** [comment]
See if master now gives you the functionality you want @thesmallestduck and @timpitman

**Comment by thesmallestduck** [comment]
@jarosser06 can confirm latest master allows for the directory structure I listed above to be deployed to a real lambda without import funny-business and for the unit tests using the same imports to be run. Thanks!

**Comment by martinb3** [comment]
:+1:

**Comment by timpitman** [comment]
Thanks, it's working for me too!
