### ISSUE TITLE
If you pass a directory in for the configuration file parameter, we should probably try to use it

### ISSUE THREAD

**Issue by martinb3** [rackerlabs/lambda-uploader#76]
Right now, if the file doesn't exist (e.g. if it's a directory), we try the current directory and join lambda.json to it. Should we consider trying the supplied path given as an argument, and joining lambda.json to that first.

**Comment by DeviaVir** [comment]
Possible breadcrumb: https://github.com/rackerlabs/lambda-uploader/pull/74#discussion_r57307712

**Comment by jarosser06** [comment]
Discussing this offline. I feel like the lambda-uploader shouldn't behave like this. If someone is overriding the configuration file default "/path/of/function/lambda.json" then it should explicitly point to a configuration file. If a directory is passed then it is not a configuration file and an exception should be raised.
