### ISSUE TITLE
Linked Library Issues

### ISSUE THREAD

**Issue by mjgorman** [rackerlabs/lambda-uploader#88]
Noticed an issue with modules with linked libraries(PyCrypto for instance), not even using your uploader but I suspect same issues would be present and it might be something cool for you guys to try and solve. If you run this uploader or pip on local OSX box and try and use those dependencies on Lambda it will fail as the ELFs are not linux compatible.

**Comment by martinb3** [comment]
Hello! We actually do have a way to do this; there's an option to take an existing virtualenv and re-use it with lambda-uploader. We use this option specifically for PyCrypto -- `lambda-uploader --virtualenv=~/.virtualenv/my_custom_virtualenv`.

In our case, we build a working virtualenv on Amazon Linux (with the correct PyCrypto binaries), and then bring it back to our local / development machine. Then we reuse that virtualenv using the flag above, uploading it along with our lambda function when doing deployments.

Hope this helps!
