### ISSUE TITLE
Ugly crash if lambda.json file has syntax error

### ISSUE THREAD

**Issue by rossy62** [rackerlabs/lambda-uploader#89]
My first attempt, I deleted the vpc section of lambda.json, and forgot to remove the trailing comma before it.  This yielded some cryptic errors not managed well for a newbie (like myself).
I'm new to gitHub, but I will try to grab the repo, and see if I can't fix this in the coming weeks (if it's not otherwise fixed).  To see if I can contribute to the effort.

Just starting up the Lambda learning curve, Thinking it's a big lever to get work done.

**Comment by jarosser06** [comment]
Would you mind giving us the output from the crash.

**Comment by jarosser06** [comment]
I assume the stack trace you received was from the JSON module. Unfortunately it would be an exceptional amount of work to capture every possible exception and convert it into something prettier.

Closing this since it has been open for a month with no further action.
